// <auto-generated />
namespace eRenting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddVeiculo_FK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddVeiculo_FK));
        
        string IMigrationMetadata.Id
        {
            get { return "202012231800388_AddVeiculo_FK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
