// <auto-generated />
namespace eRenting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddReserva_FKVeiculo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReserva_FKVeiculo));
        
        string IMigrationMetadata.Id
        {
            get { return "202012232112012_AddReserva_FKVeiculo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
